// <auto-generated />
namespace Project_REMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class transactionproperty1m : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(transactionproperty1m));
        
        string IMigrationMetadata.Id
        {
            get { return "202306091920428_transaction-property-1-m"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
